### ISSUE TITLE
Documentatie

### ISSUE THREAD

**Issue by Marzus** [Marzus/ProiectAndroid#6]
**Cica e doar 15 puncte din nota totala!!!**

Documentul este formatat cu Times New Roman 12pt. (sau Calibri 11pt) si spațiere la 1 rînd.

1 Introducere (1/2 - 1 pag.)

-     Definire problema (ce problema rezolva proiectul?);
-     Definire obiective (ce face proiectul pentru a rezolva problema?);
-     Definire cadru general (in ce mediu va fi folosita aplicația?);

2 Descriere soluție (4 - 8 pag)

-     NU se fac referiri la tehnologiile folosite;
-     Descriere scenariu utilizare;
-     Descriere funcționalități;

3 Implementare soluție pentru platforma Android (6 - 10 pag.)

-     Descriere tehnica a modului de implementare a funcționalităților prezentate in capitolul 2;
-     Secvențe de cod de maxim 1/2 pagină;
-     Capturi de ecran;
-     Probleme/avantaje identificate la implementare pentru platforma Android;
-     Jumătate din capitol reprezintă text (NU imagini sau cod);

5 Concluzii (1/2 - 1 pag.)

-     Opinie proprie cu   privire la cea mai buna soluție tehnică pentru a implementa aplicația respectivă;

Bibliografie
Anexe (maxim 5 pag)

**Comment by ghost** [comment]
Am scris o parte din documentatie. E pe Google Docs la linkul:
https://docs.google.com/document/d/1Rfzy9qEDbIoElXcs-mltLvttDsHxg2Dtd3n6eT4OAHk/edit?usp=sharing

Mai am de scris la partea a doua maine dupa-amiaza. Partea a 3a este legata de tehnic si zic sa lasam la final ca poate modificam ceva si sa nu reiteram codurile si screenshoturile si in documentatie.

**Comment by ghost** [comment]
Prima faza la documentatie.
[AndroidProjectDocumentation.pdf](https://github.com/Marzus/ProiectAndroid/files/657178/AndroidProjectDocumentation.pdf)

**Comment by ghost** [comment]
A doua faza(finala) la documentatie.
[AndroidProjectDocumentation (1).pdf](https://github.com/Marzus/ProiectAndroid/files/706817/AndroidProjectDocumentation.1.pdf)
